#ifndef JDECOMPILER_JDECOMPILER_INSTANCE_CPP
#define JDECOMPILER_JDECOMPILER_INSTANCE_CPP

#undef inline
#include <filesystem>
#define inline INLINE
#include "util.cpp"

namespace jdecompiler {

	struct JDecompiler {

		protected:
			static const JDecompiler* instance;


			const string progName;

			const vector<BinaryInputStream*> files;
			const bool atLeastOneFileSpecified;

			const char* const indent;

			const bool failOnError;

			enum class ConstantsUsage { ALWAYS, MINIMAL, NEVER };
			const ConstantsUsage useConstants;
			const bool useCustomConstants;

			enum class HexUsage { ALWAYS, AUTO, NEVER };
			const HexUsage useHexNumbers;

			const bool useShortArrayInitializing;
			const bool canShowSynthetic, canShowBridge, canShowAutogenerated;

			mutable map<string, const Class*> classes;

			JDecompiler(const string progName, const vector<BinaryInputStream*>& files, bool atLeastOneFileSpecified, const char* indent,
					bool failOnError, ConstantsUsage useConstants, bool useCustomConstants, HexUsage useHexNumbers,
					bool useShortArrayInitializing, bool canShowSynthetic, bool canShowBridge, bool canShowAutogenerated,
					map<string, const Class*>& classes):

					progName(progName), files(files), atLeastOneFileSpecified(atLeastOneFileSpecified), indent(indent),
					failOnError(failOnError), useConstants(useConstants), useCustomConstants(useCustomConstants), useHexNumbers(useHexNumbers),
					useShortArrayInitializing(useShortArrayInitializing),
					canShowSynthetic(canShowSynthetic), canShowBridge(canShowBridge), canShowAutogenerated(canShowAutogenerated),
					classes(classes) {}



		public:
			static const JDecompiler& getInstance() {
				if(instance == nullptr)
					throw IllegalStateException("JDecompiler yet not initialized");
				return *instance;
			}

			static bool init(int argc, const char* args[]) {
				if(instance != nullptr)
					throw IllegalStateException("JDecompiler already initialized");

				const string progPath = args[0];
				const string progName = progPath.substr(progPath.find_last_of(std::filesystem::path::preferred_separator) + 1);

				vector<BinaryInputStream*> files;

				int_fast32_t indentWidth = 4;
				const char* indent = "    ";

				bool failOnError = false;
				ConstantsUsage useConstants = ConstantsUsage::ALWAYS;
				bool useCustomConstants = true;
				HexUsage useHexNumbers = HexUsage::NEVER;

				bool useShortArrayInitializing = true;
				bool canShowSynthetic = false, canShowBridge = false, canShowAutogenerated = false;

				map<string, const Class*> classes;


				if(argc <= 1) {
					cout << "Usage: " << progName << " [options] <class-files>" << endl;
					return false;
				}

				#define printError(...) cerr << progName << ": error: " << __VA_ARGS__ << endl
				#define printErrorAndExit(...) { printError(__VA_ARGS__); return false; }

				#define requireValue() {\
					if(!hasValue) {\
						printErrorAndExit("option " << option << " required value");\
						return false;\
					}\
					i++;\
				}

				bool isIndentWidthSpecified = false;

				bool atLeastOneFileSpecified = false;

				for(int i = 1; i < argc; i++) {
					const string arg = args[i];
					const size_t length = arg.size();

					if(length > 1 && arg[0] == '-') {

						string option, value;
						bool hasValue = false, hasValueWeak = false;
						const auto splitpos = arg.find('=');

						if(splitpos != string::npos) {
							option = string(arg, 0, splitpos);
							value = string(arg.begin() + splitpos + 1, arg.end());
							hasValue = hasValueWeak = true;
						} else {
							option = arg;
							if(i + 1 < argc) {
								value = args[i + 1];
								hasValue = true;
							}
						}


						if(option == "-h" || option == "--help" || option == "-?") {
							cout << "Usage: " << progName << " [options] <class-files>\n"
								"\n"
								"  -h, --help, -?                      show this message and exit\n"
								"  -f, --fail-on-error                 fail on error\n"
								"  -w=<width>, --indent-width=<width>  set indent width (by default 4)\n"
								"  -i=<indent>, --indent=<indent>      set indent (by default four spaces)\n"
								"  -tab                                use tabs (equivalent to --indent='\\t')\n"
								"\n"
								"  --use-constants=auto|min|never      use constants:\n"
								"                                auto    use for all standart constants (MAX_VALUE, MIN_VALUE, etc.)\n"
								"                                 min    use for only POSITIVE_INFINITY, NEGATIVE_INFINITY and NaN\n"
								"                               never    don't use constants at all\n"
								"  --no-custom-consts                      don't use custom constants (which declared in decompiled class)\n"
								"  --min-consts                            the same as --use-constants=min\n"
								"  --no-consts                             the same as --use-constants=never\n"
								"  --hex[=always|auto|never]           use hex numbers:\n"
								"                              always    always use\n"
								"                                auto    only use for values like 0x7F, 0x80 and 0xFF\n"
								"                               never    do not use (by default)\n"
								"\n"
								"  --no-short-array-init               do not use short array initialization in the variable declaration\n"
								"  --synthetic                         show synthetic fields, methods and classes generated by compiler\n"
								"  --bridge                            show bridge methods generated by compiler\n"
								"  --autogenerated                     show methods autogenerated by compiler\n"
								"                                        (such as Enum.valueOf(String) or constructor by default)\n"
								"  --all-autogenerated                 show synthetic, bridge and autogenerated fields, methods and classes" << endl;

							return false;

						} else if(option == "-f" || option == "--fail-on-error") {
							failOnError = true;

						} else if(option == "-w" || option == "--indent-width") {
							requireValue();
							try {
								indentWidth = stoi(value);
								if(indentWidth < 0)
									printErrorAndExit("indent width " << value << " cannot be negative");
								if(indentWidth > 16)
									printErrorAndExit("indent width " << value << " is out of range (valid values are from 0 to 16)");

								indent = repeatString(indent, indentWidth);
							} catch(const invalid_argument&) {
								printErrorAndExit("Invalid argument value: '" << value << '\'');
							} catch(const out_of_range&) {
								printErrorAndExit("Argument value '" << value << "' is out of range");
							}

							isIndentWidthSpecified = true;

						} else if(option == "-i" || option == "--indent") {
							requireValue();
							value = unescapeString(value);
							indent = repeatString(value, isIndentWidthSpecified || value != "\t" ? indentWidth : (indentWidth = 1));

						} else if(option == "-tab") {
							indent = "\t";

						} else if(option == "--use-constants") {
							requireValue();

							if(value == "always")
								useConstants = ConstantsUsage::ALWAYS;
							else if(value == "min")
								useConstants = ConstantsUsage::MINIMAL;
							else if(value == "never")
								useConstants = ConstantsUsage::NEVER;
							else
								printErrorAndExit("invalid value for option " << option << ": only valid always, min or never");

						} else if(option == "--no-custom-consts") {
							useCustomConstants = false;

						} else if(option == "--min-consts") {
							useConstants = ConstantsUsage::MINIMAL;

						} else if(option == "--no-consts") {
							useConstants = ConstantsUsage::NEVER;

						} else if(option == "--hex") {
							if(hasValueWeak) {
								if(value == "always")     useHexNumbers = HexUsage::ALWAYS;
								else if(value == "auto")  useHexNumbers = HexUsage::AUTO;
								else if(value == "never") useHexNumbers = HexUsage::NEVER;
								else printErrorAndExit("invalid value for option " << option << ": only valid always, auto or never");
							} else {
								useHexNumbers = HexUsage::AUTO;
							}

						} else if(option == "--no-short-array-init") {
							useShortArrayInitializing = false;
						} else if(option == "--synthetic") {
							canShowSynthetic = true;
						} else if(option == "--bridge") {
							canShowBridge = true;
						} else if(option == "--autogenerated") {
							canShowAutogenerated = true;
						} else if(option == "--all-autogenerated") {
							canShowSynthetic = true;
							canShowBridge = true;
							canShowAutogenerated = true;
						} else {
							printErrorAndExit("Unknown argument " << arg << "\n"
								"Use " << progName << " --help for more information");
						}
					} else {
						atLeastOneFileSpecified = true;
						try {
							files.push_back(new BinaryInputStream(arg));
						} catch(const IOException& ex) {
							printError(ex.what());
						}
					}
				}

				#undef requireValue
				#undef printErrorAndExit

				instance = new JDecompiler(progName, files, atLeastOneFileSpecified, indent,
						failOnError, useConstants, useConstants == ConstantsUsage::ALWAYS && useCustomConstants, useHexNumbers,
						useShortArrayInitializing, canShowSynthetic, canShowBridge, canShowAutogenerated, classes);

				return true;
			}


			inline const char* getIndent() const {
				return indent;
			}

			inline bool isFailOnError() const {
				return failOnError;
			}

			inline bool canUseConstants() const {
				return useConstants == ConstantsUsage::ALWAYS;
			}

			inline bool canUseCustomConstants() const {
				return useCustomConstants;
			}

			inline bool canUseNaNAndInfinity() const {
				return useConstants == ConstantsUsage::ALWAYS || useConstants == ConstantsUsage::MINIMAL;
			}

			inline bool canUseHexNumbers() const {
				return useHexNumbers == HexUsage::AUTO || useHexNumbers == HexUsage::ALWAYS;
			}

			inline bool useHexNumbersAlways() const {
				return useHexNumbers == HexUsage::ALWAYS;
			}

			inline bool canUseShortArrayInitializing() const {
				return useShortArrayInitializing;
			}

			inline bool showSynthetic() const {
				return canShowSynthetic;
			}

			inline bool showBridge() const {
				return canShowBridge;
			}

			inline bool showAutogenerated() const {
				return canShowAutogenerated;
			}

			inline const vector<BinaryInputStream*>& getFiles() const {
				return files;
			}

			void readClassFiles() const;

			inline const map<string, const Class*>& getClasses() const {
				return classes;
			}

			inline const Class* getClass(const string& name) const {
				const auto& classIterator = classes.find(name);
				return classIterator != classes.end() ? classIterator->second : nullptr;
			}

			inline bool hasClass(const string& name) const {
				return getClass(name) != nullptr;
			}

		protected:
			template<typename Arg, typename... Args>
			static inline void print(ostream& out, Arg arg, Args... args) {
				if constexpr(sizeof...(Args) != 0)
					print(out << arg, args...);
				else
					out << arg << endl;
			}

		private:
			template<typename... Args>
			inline void error(Args... args) const {
				print(cerr << progName << ": error: ", args...);
			}
	};

	const JDecompiler* JDecompiler::instance = nullptr;
}

#endif
