#!/bin/sh
JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
g++ -std=c++17 -shared -fPIC -I"$JAVA_HOME/include/" -I"$JAVA_HOME/include/linux/" -L"/usr/bin/java" -L"$JAVA_HOME/lib/server/" "$@" jvm.cpp -ljvm -o jvm.so
